name       : variety
homepage   : https://launchpad.net/variety
version    : 0.6.3
release    : 7
source     :
    - https://launchpad.net/variety/trunk/0.6.3/+download/variety_0.6.3-0-581-201611011859-ubuntu16.04.1.tar.gz : 30f82e606a090dfab463f29500ec9dd9ad78fcfcd5a96c5f0f5d0b2bd9ce79eb
license    : GPL-3.0
component  : multimedia.graphics
summary    : Variety changes the wallpaper on a regular interval using user-specified or automatically downloaded images.
description: |
    Variety changes the desktop wallpaper on a regular basis, using user-specified or automatically downloaded images.
    Variety sits conveniently as an indicator in the panel and can be easily paused and resumed. The mouse wheel can be used to scroll wallpapers back and forth until you find the perfect one for your current mood.
    part from displaying images from local folders, several different online sources can be used to fetch wallpapers according to user-specified criteria.
    Variety can also automatically apply various fancy filters to the displayed images - charcoal painting, oil painting, heavy blurring, etc. - so that your desktop is always fresh and unique. Applying a heavy blurring filter for example is a great way to get abstract-looking and unobtrusive, yet colorful wallpapers, similar in spirit to the default one in Ubuntu.
builddeps  :
    - desktop-file-utils
    - intltool
    - python-beautifulsoup4
    - python-configobj
    - python-cssselect
    - python-distutils-extra
    - python-pycurl
    - pkgconfig(dbus-python)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libnotify)
    - pkgconfig(MagickCore)
    - pkgconfig(pycairo)
    - pkgconfig(pygobject-2.0)
rundeps    :
    - libwebkit3-gtk
    - python-pillow
    - pyexiv2
    - python-beautifulsoup4
    - python-configobj
    - python-lxml
install    : |
    unset srcdir
    %python_install
