name       : variety
version    : 0.6.0
release    : 3
source     :
    - https://launchpad.net/variety/trunk/0.6.0/+download/variety_0.6.0.tar.gz : f3760ac546073bb68f840f5eafffaf6a265e5be39aaa36462ff74547fe0594d0
license    : GPL-3.0
summary    : Variety changes the wallpaper on a regular interval using user-specified or automatically downloaded images.
description: |
    Variety changes the desktop wallpaper on a regular basis, using user-specified or automatically downloaded images.
    Variety sits conveniently as an indicator in the panel and can be easily paused and resumed. The mouse wheel can be used to scroll wallpapers back and forth until you find the perfect one for your current mood.
    part from displaying images from local folders, several different online sources can be used to fetch wallpapers according to user-specified criteria.
    Variety can also automatically apply various fancy filters to the displayed images - charcoal painting, oil painting, heavy blurring, etc. - so that your desktop is always fresh and unique. Applying a heavy blurring filter for example is a great way to get abstract-looking and unobtrusive, yet colorful wallpapers, similar in spirit to the default one in Ubuntu.
component  : desktop.multimedia
rundeps    :
    - python-pillow
    - pyexiv2
    - python-lxml
    - python-beautifulsoup4
builddeps  :
    - desktop-file-utils
    - intltool
    - python-beautifulsoup4
    - python-configobj
    - python-cssselect
    - python-distutils-extra
    - python-pycurl
    - pkgconfig(dbus-python)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libnotify)
    - pkgconfig(MagickCore)
    - pkgconfig(pycairo)
    - pkgconfig(pygobject-2.0)
install    : |
    unset srcdir
    python setup.py install --root=%installroot% --no-compile -O0
