name       : variety
homepage   : https://launchpad.net/variety
version    : 0.6.9
release    : 14
source     :
    - https://github.com/varietywalls/variety/archive/0.6.9.tar.gz : 4f8022457e72aa91f5e19ee7cac66e2efba58cc508b4928d45f33888b76b92a4
license    : GPL-3.0-or-later
component  : multimedia.graphics
summary    : Variety changes the wallpaper on a regular interval using user-specified or automatically downloaded images
description: |
    Variety sits conveniently as an indicator in the panel and can be easily paused and resumed. The mouse wheel can be used to scroll wallpapers back and forth until you find the perfect one for your current mood.
    Apart from displaying images from local folders, several different online sources can be used to fetch wallpapers according to user-specified criteria.
    Variety can also automatically apply various fancy filters to the displayed images - charcoal painting, oil painting, heavy blurring, etc. - so that your desktop is always fresh and unique. Applying a heavy blurring filter for example is a great way to get abstract-looking and unobtrusive, yet colorful wallpapers, similar in spirit to the default one in Ubuntu.
builddeps  :
    - pkgconfig(dbus-python)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libnotify)
    - pkgconfig(MagickCore)
    - pkgconfig(pycairo)
    - pkgconfig(pygobject-2.0)
    - desktop-file-utils
    - intltool
    - python-beautifulsoup4
    - python-configobj
    - python-cssselect
    - python-distutils-extra
    - python-pycurl
rundeps    :
    - gexiv2
    - libappindicator
    - pyexiv2
    - python-beautifulsoup4
    - python-cairo
    - python-configobj
    - python-lxml
    - python-pillow
install    : |
    #unset srcdir
    %python_install
