name       : variety
homepage   : http://peterlevi.com/variety
version    : 0.8.1
release    : 18
source     :
    - https://github.com/varietywalls/variety/archive/0.8.1.tar.gz : c33f0d203748bb858146d5c1de0a4b2b4766a0441a30eacc0881f0ffe0a28d46
license    : GPL-3.0-or-later
component  : multimedia.graphics
summary    : Variety changes the wallpaper on a regular interval using user-specified or automatically downloaded images
description: |
    Variety sits conveniently as an indicator in the panel and can be easily paused and resumed. The mouse wheel can be used to scroll wallpapers back and forth until you find the perfect one for your current mood.
    Apart from displaying images from local folders, several different online sources can be used to fetch wallpapers according to user-specified criteria.
    Variety can also automatically apply various fancy filters to the displayed images - charcoal painting, oil painting, heavy blurring, etc. - so that your desktop is always fresh and unique. Applying a heavy blurring filter for example is a great way to get abstract-looking and unobtrusive, yet colorful wallpapers, similar in spirit to the default one in Ubuntu.
builddeps  :
    - python-distutils-extra
rundeps    :
    - gexiv2
    - imagemagick
    - libgtk-3
    - libnotify
    - python-beautifulsoup4
    - python-configobj
    - python-httplib2
    - python-lxml
    - python-pillow
    - python-pycurl
    - python-requests
    - python3-cairo
    - python3-dbus
    - python3-gobject
    - xdg-user-dirs
install    : |
    %python3_install
    rm -rf $installdir/usr/share/doc
